### ISSUE TITLE
N6G Requires Spiked Hat (or a frame-perfect trick, perhaps?)

### ISSUE THREAD

**Issue by jet082** [AaronDobbe/wl3-randomizer#1]
As title says.

**Comment by AaronDobbe** [comment]
Does it? N6 Green is the one where you ground-pound the hard blocks near the start and enter the door, then do the rolling puzzle room to get the key and chest.

You might be thinking of N6S (silver), which *does* require the helmet in logic?

**Comment by jet082** [comment]
I was misreading this.
